"""Initial schema: users, categories, todos

Revision ID: 096e1bae97be
Revises: 
Create Date: 2026-01-09 00:59:03.607059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '096e1bae97be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('idx_categories_user_name', 'categories', ['user_id', 'name'], unique=True)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 4', name='check_priority_range'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_todos_category_id', 'todos', ['category_id'], unique=False)
    op.create_index('idx_todos_user_completed', 'todos', ['user_id', 'is_completed'], unique=False)
    op.create_index('idx_todos_user_due_date', 'todos', ['user_id', 'due_date'], unique=False, postgresql_where='due_date IS NOT NULL')
    op.create_index('idx_todos_user_id', 'todos', ['user_id'], unique=False)
    op.create_index('idx_todos_user_priority', 'todos', ['user_id', 'priority'], unique=False)
    op.create_index(op.f('ix_todos_category_id'), 'todos', ['category_id'], unique=False)
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_category_id'), table_name='todos')
    op.drop_index('idx_todos_user_priority', table_name='todos')
    op.drop_index('idx_todos_user_id', table_name='todos')
    op.drop_index('idx_todos_user_due_date', table_name='todos', postgresql_where='due_date IS NOT NULL')
    op.drop_index('idx_todos_user_completed', table_name='todos')
    op.drop_index('idx_todos_category_id', table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_index('idx_categories_user_name', table_name='categories')
    op.drop_index('idx_categories_user_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
